### ISSUE TITLE
add icon for customer visibilty

### ISSUE THREAD

**Issue by trowik** [adfinis-sygroup/timed-frontend#530]
Some projects are marked as customer visible and comments from these projects are visible for the customer.
Right now timed users don't know whether a comment is visible for the customer or not.
I propose to add an icon at the end of the comment field to show that feature. 
Additionally I would add a hover-hint to explain the icon.

![timed_customer_visible](https://user-images.githubusercontent.com/55092761/113859432-2e78d180-97a5-11eb-961a-e072a1f1baa4.png)

Is there a better solution or a different approach to that? Any suggestions?

**Comment by czosel** [comment]
I like the idea 👍

**Comment by aziiee** [comment]
Implemented in #562 
Bug reported by @tongpu fixed in #639. The icon is still inside the input field, but with some padding so the text doesn't collide.

@trowik Thanks!
